 # FDM (IFDM)

### Black Scholes PDE

$
F_t + (r-d)SF_S + F_{SS} \frac{\sigma^2 S^2 }{2} = rF
$

$$ \\ $$

Backward Difference (Implicit finite difference method)
$$ \\ $$

$
\frac{F(t+\Delta t) - F(t)}{\Delta t} + (r-d)S \bullet \frac{F(S+\Delta S) - F(S - \Delta S)}{2\Delta S} + \frac{\sigma^2 S^2}{2}\frac{F(S + \Delta S) - 2 F(S) + \Delta (S - \Delta S)}{{(\Delta S)}^2} = rF(t,S)
$

$S = n \times \Delta S $라고 가정하자. $S + \Delta S = \Delta S \bullet (n+1)$이고, $S - \Delta S = \Delta S \bullet (n-1)$

$$
\frac{F(n,t+\Delta t) - F(n,t)}{\Delta t} + (r-d)(n \bullet \Delta S)  \frac{F{(n+1,t)} - F{(n-1,t)}}{2\Delta S} + \frac{{(\sigma n \Delta S)}^2}{2} \frac{F{(n + 1,t)} - 2F(n,t)+ F(n-1,t)}{{(\Delta S)}^2} \\ \ \\ = rF(n,t) $$

$$ \\ $$
따라서  n번째 주가 node에서 파생상품 가치는 다음과 같다.


$$ \frac{F_{n}^{t+\Delta t} - F_{n}^{t}}{\Delta t} + (r-d)n \frac{ ({F_{n+1}^{t} - F_{n-1}^{t}})}{2} + \frac{{(\sigma n)}^2}{2} {(F_{n + 1}^{t} - 2F_{n}^{t} + F_{n - 1}^{t})} = rF_{n}^{t}
$$

$$
V_n^{t+\Delta t} = 0.5 \Delta t  \bullet ((r-d)n - \sigma^2 n^2) V_{n-1}^{t} + \\ 
(1+ \Delta t(r + \sigma^2 n^2)) V_n^t + \\
0.5\Delta t ( -(r-d)n - \sigma^2 n^2 )V_{n+1}^t
$$

 ## 쉽게 표현하면 다음과 같다.
 핵심)
 $
 F_n^{t+\Delta t} = a_n F_{n-1}^{t }  + b_n F_{n}^{t }+ c_n F_{n+1}^{t }
 $
 
 $$
 a_n = 0.5 \Delta t  \bullet ((r-d)n - \sigma^2 n^2) \\ \ \\ 
 b_n = 1+ \Delta t(r + \sigma^2 n^2) \\ \ \\ 
 c_n = 0.5\Delta t ( -(r-d)n - \sigma^2 n^2 )\\ \ \\
 $$
 
 n = 0 ~ N까지 있다고 가정하자. 시간에 관계없이 파생상품 가치의 끝 부분만 다음과 같이 부드럽게 처리하자. (주가가 0일 때, 주가가 매우 높을때)
 
$ F_{N+1} = 2 F_{N} -  F_{N-1}$

$ F_{-1} = 2 F_{0} - F_{1}$ 

위 핵심 식에 n=0을 넣으면
$$
 F_0^{t+\Delta t} = a_0 F_{-1}^{t }  + b_0 F_{0}^{t }+ c_0 F_{1}^{t } =   a_0(2F_{0}^t - F_{1}^t)+ b_0 F_{0}^{t }+ c_0 F_{1}^{t }
\\  = (2a_0 + b_0) F_0 + (c_0 - a_0)F_1
 $$
 
같은방식으로 위 식에 n = N을 넣으면
$$
F_N^{t+\Delta t} = (a_N - c_N) F_{N-1} + (b_N + 2 c_N)F_{N}
$$
이다.



고로 다음 연립방정식이 성립한다. (N = 200이라고 가정하자.)

$
F_0^{t+\Delta t} = (2a_0 + b_0) F_0 + (c_0 - a_0)F_1
$

$
F_1^{t+\Delta t} = a_1 F_{0}^{t }  + b_1 F_{1}^{t }+ c_1 F_{2}^{t }
$

$
F_2^{t+\Delta t} = a_2 F_{1}^{t }  + b_2 F_{2}^{t }+ c_2 F_{3}^{t }
$

...

$
F_{199}^{t+\Delta t} = a_{199} F_{198}^{t }  + b_{199} F_{199}^{t }+ c_{199} F_{200}^{t }
$

$
F_{200}^{t+\Delta t} = (a_{200} - c_{200}) F_{199} + (b_{200} + 2c_{200}) F_{200}
$

$
\begin{bmatrix} b_0 + 2a_0 & c_0-a_0 & 0 & 0& .. & 0& 0 & 0\\ a_1 & b_1 & c_1& 0& ..& 0 & 0& 0 \\ 0 & a_2 & b_2& c_2& ..& 0 & 0& 0\\ 0 & 0 & a_3& b_3& ..& 0& 0& 0\\ .. & .. & ..& ..& ..& 0& 0& 0\\ 0 & 0 & 0& 0& ..& a_{N-1} & b_{N-1}& c_{N-1}\\ 0 & 0 & 0& 0& 0& 0& a_{N}-c_{N}& b_{N}+2c_{N} \end{bmatrix}
\begin{bmatrix} F_0^{m} \\ F_1^{m} \\ F_2^{m}\\ ...\\ ...\\ F_{N-1}^{m}\\ F_{N}^{m}\end{bmatrix} = 
$
$
\begin{bmatrix} F_0^{m+1} \\ F_1^{m+1} \\ F_2^{m+1}\\ ...\\ ...\\ F_{N-1}^{m+1}\\ F_{N}^{m+1}\end{bmatrix}
$

이 방법대로 미래 Payoff부터 현재까지 시간과 주가 수준에 대한 모든 Grid를 계산 하면 된다.

$
\begin{bmatrix} b_0 + 2a_0 & c_0-a_0 & 0 & 0& .. & 0& 0 & 0\\ a_1 & b_1 & c_1& 0& ..& 0 & 0& 0 \\ 0 & a_2 & b_2& c_2& ..& 0 & 0& 0\\ 0 & 0 & a_3& b_3& ..& 0& 0& 0\\ .. & .. & ..& ..& ..& 0& 0& 0\\ 0 & 0 & 0& 0& ..& a_{N-1} & b_{N-1}& c_{N-1}\\ 0 & 0 & 0& 0& 0& 0& a_{N}-c_{N}& b_{N}+2c_{N} \end{bmatrix} = Tdiag
$이고,


$
\begin{bmatrix} F_0^{m} \\ F_1^{m} \\ F_2^{m}\\ ...\\ ...\\ F_{N-1}^{m}\\ F_{N}^{m}\end{bmatrix} = {Tdiag}^{-1} \bullet \begin{bmatrix} F_0^{m+1} \\ F_1^{m+1} \\ F_2^{m+1}\\ ...\\ ...\\ F_{N-1}^{m+1}\\ F_{N}^{m+1}\end{bmatrix}$

 ## Practice FDM Call Option Pricing
 
 n = 0~200

 r = 0.05
 
 div = 0.02
 
 T = 1
 
 dt = 1/365
 
 $\sigma$ = 0.2
 
 $S_0 = 100\% $ (100번째 node)
 
 행사가격이 90%인 콜옵션의 가치를 계산해보자.

In [1]:
import numpy as np
import pandas as pd
from scipy.sparse import diags
from scipy.stats import norm
N = 200
T = 1
r, div = 0.05, 0.02
sigma = 0.2
S = 100
K = 90
dt = 1/365
Ntime = int(T/dt)
n = np.arange(0,N+1,1)
Grid = np.zeros((N+1, Ntime))

In [2]:
payoff = np.maximum(n-K,0)
Grid[:,Ntime-1] = payoff

In [3]:
pd.DataFrame(Grid[:,-1:], columns = ['Final_Value'])

     Final_Value
0            0.0
1            0.0
2            0.0
3            0.0
4            0.0
..           ...
196        106.0
197        107.0
198        108.0
199        109.0
200        110.0

[201 rows x 1 columns]

In [4]:
an = 0.5 * dt*((r-div)*n-sigma**2*n**2)
bn = 1+dt*(r+sigma**2*n**2)
cn = 0.5 * dt * (-(r-div)*n - sigma**2*n**2)
a0 , b0 , c0 = an[0], bn[0], cn[0]
aN , bN, cN = an[-1],bn[-1],cn[-1]
bn[0] = 2*a0 + b0
cn[0] = c0-a0
bn[-1] = bN +2*cN
an[-1] = aN - cN 
k = np.array([an[1:], bn, cn[:-1]], dtype = object)
offset = [-1,0,1]
tdiag = diags(k,offset).toarray()
int_tdiag = np.linalg.inv(tdiag)

In [5]:
for i in range(1,Ntime)[::-1] :
    Grid[:,i-1:i] = int_tdiag.dot(Grid[:,i:i+1]).round(7)

In [6]:
pd.DataFrame(Grid)

,0,1,2,3,4,5,6,7,8,9,...,355,356,357,358,359,360,361,362,363,364
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,106.506989,106.505785,106.504581,106.503376,106.502169,106.500962,106.499754,106.498544,106.497334,106.496123,...,106.014252,106.012673,106.011093,106.009511,106.007929,106.006345,106.004761,106.003175,106.001588,106.0
197,107.487216,107.486067,107.484916,107.483766,107.482613,107.481460,107.480306,107.479151,107.477995,107.476838,...,107.013759,107.012235,107.010709,107.009182,107.007655,107.006126,107.004596,107.003065,107.001533,107.0
198,108.467443,108.466348,108.465253,108.464156,108.463058,108.461959,108.460860,108.459759,108.458657,108.457554,...,108.013266,108.011796,108.010326,108.008854,108.007381,108.005907,108.004432,108.002956,108.001478,108.0
199,109.447671,109.446631,109.445589,109.444547,109.443504,109.442459,109.441413,109.440367,109.439319,109.438270,...,109.012773,109.011358,109.009942,109.008525,109.007107,109.005688,109.004267,109.002846,109.001424,109.0
200,110.427900,110.426914,110.425927,110.424938,110.423949,110.422959,110.421967,110.420975,110.419981,110.418987,...,110.012280,110.010920,110.009558,110.008196,110.006833,110.005469,110.004103,110.002736,110.001369,110.0

In [7]:
Grid[S,0]

15.1074252

 ## Black Scholes Call Price

In [8]:
d1 = (np.log(S/K) + (r-div+0.5*sigma**2)*T)/(sigma * np.sqrt(T))
d2 = d1 - sigma * np.sqrt(T)
C = S * np.exp(-div * T) * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)

In [9]:
C

15.123708071023735